/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'error-container': '#93000a',
        'on-surface': '#e5e1e4',
        'tertiary-container': '#fed83a',
        'secondary-container': '#571bc1',
        'outline': '#849495',
        'on-secondary-container': '#c4abff',
        'inverse-primary': '#00696f',
        'tertiary': '#fff6e4',
        'on-error-container': '#ffdad6',
        'inverse-surface': '#e5e1e4',
        'background': '#131315',
        'surface-bright': '#39393b',
        'on-primary-container': '#006a71',
        'on-background': '#e5e1e4',
        'surface': '#131315',
        'surface-container-highest': '#353437',
        'tertiary-fixed': '#ffe173',
        'on-primary': '#00363a',
        'surface-variant': '#353437',
        'on-tertiary': '#3b2f00',
        'primary-container': '#00f2ff',
        'surface-tint': '#00dbe7',
        'on-tertiary-container': '#725e00',
        'surface-container-lowest': '#0e0e10',
        'inverse-on-surface': '#303032',
        'on-secondary': '#3c0091',
        'primary-fixed': '#74f5ff',
        'on-error': '#690005',
        'surface-container': '#201f21',
        'surface-container-high': '#2a2a2c',
        'surface-dim': '#131315',
        'secondary-fixed-dim': '#d0bcff',
        'primary': '#e1fdff',
        'primary-fixed-dim': '#00dbe7',
        'on-secondary-fixed': '#23005c',
        'secondary': '#d0bcff',
        'error': '#ffb4ab',
        'on-surface-variant': '#b9cacb',
        'surface-container-low': '#1b1b1d',
        'on-primary-fixed': '#002022',
        'outline-variant': '#3a494b',
        'secondary-fixed': '#e9ddff',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
